Makefile: Fix invalid golangci-lint run arguments
When running the `analyze` Makefile target locally:

```bash
$ make analyze
GOTOOLCHAIN=go1.24.1 go tool golangci-lint run --fast --verbose ./...
Error: unknown flag: --fast
Failed executing command with error: unknown flag: --fast
make: *** [Makefile:169: analyze] Error 3
```

We bumped golangci-lint from v1 to v2 relatively recently and the
--fast CLI flag is no longer supported.

Signed-off-by: timflannagan <timflannagan@gmail.com>